### ISSUE TITLE
Increase coverage to at least 75%

### ISSUE THREAD

**Issue by ItsDrike** [py-mine/mcproto#10]
There was a lot of new code written which doesn't yet have any unit-tests covering it.

Increasing this coverage is absolutely necessary before making the next major release (which will be the first full release), as without it the automated test workflows aren't running all of the code, and there might be some things which were missed and are potentially version incompatible, or just plain broken.

Alongside, it could be a good idea to also add some integration tests, running the examples in readme or similar things, ensuring that everything works properly when put together.

Note that the 75% in the title is just a suggestion, ideally, this should be 100%, but that's probably unrealistic, however generally, we should try to make the coverage as high as possible.

**Comment by ItsDrike** [comment]
Note: While I did assign myself to this issue and I do plan on working on this, any help would be appreciated as there's a lot to cover.

If you are interested in helping out, leave a comment to this issue, describing what exactly do you wish to work on, just so that you don't accidentally end up doing something that I'm already doing myself.

**Comment by Martysh12** [comment]
Hello! I'd like to work on this.
